/**
 * Renders `compose.models.yml`: one `llama-server` service per model in the
 * chosen tier, wired for the chosen backend.
 *
 * `cuda` and `musa` have no hardware anywhere in this project (spec §3.4).
 * Their whole acceptance bar is this module's output: the five snapshots
 * under `tests/snapshots/`, asserted byte-for-byte, plus a `docker compose
 * config` validation (deferred to Task 9, which is the first place
 * `compose.local.yml` exists). Nothing here ever runs a GPU. At run time,
 * `scripts/verify-backend.sh` is what would catch a wrong device wiring —
 * this module only renders it.
 *
 * Emitted as text, not via a YAML library: this package is stdlib-only, and
 * the shape needed (a small, fixed set of mapping/sequence patterns) is
 * easier to get byte-exact by hand than to coax out of a generic serializer.
 * No Compose merge tags (`!reset`, `!override`) are ever emitted, so the
 * output works unchanged on Compose 2.35.1 (this project's dev host) through
 * 5.5.1 (the server).
 *
 * Healthcheck probe: `curl`, verified present in the `ghcr.io/ggml-org/
 * llama.cpp` server images (`:server`, `:server-cuda`, `:server-vulkan`,
 * `:server-intel` all checked directly with `docker run --entrypoint sh ...
 * which curl`; see the task report for the raw output). These are Ubuntu
 * 24.04/26.04 bases, unlike LiteLLM's Wolfi image (no curl/wget, python3
 * only) a few directories over in `compose.yml` -- the two lessons look
 * alike but the binaries available are not the same, so each healthcheck
 * was verified independently rather than copied.
 *
 * GPU backends also get `--verbosity 4`: verified on real Intel/Iris Xe
 * hardware (Task 11) that llama-server's *default* verbosity (3) emits
 * nothing at all about which device it initialised -- not the signature
 * `scripts/verify-backend.sh` looks for, not even the device's name. At
 * `--verbosity 4` the log gains exactly the lines that prove (or disprove)
 * real GPU use -- `llama_prepare_model_devices: using device <Name> ...`
 * and `load_tensors: offloaded N/N layers to GPU` -- without the firehose
 * of per-layer/per-token debug output `-lv 99` turns on. Without this flag,
 * `verify-backend.sh` cannot ever pass or fail correctly on a GPU backend;
 * it would just find an empty log. `cpu` keeps its default verbosity: its
 * signature check is a no-op (`BACKEND_SIGNATURES.cpu === null`), so there
 * is nothing here for extra verbosity to prove.
 */

import type { Backend } from "./backend.ts";
import type { ModelEntry } from "./manifest.ts";

export interface ComposePlan {
  backend: Backend;
  image: string;
  threads: number;
  models: Array<{ entry: ModelEntry; service: string }>;
}

const BANNER = "# GENERATED by bin/prepare.sh -- do not edit by hand.";

// Backends that offload to a GPU get `--n-gpu-layers 999` (offload every
// layer) instead of `--threads N`. `cpu` is the only backend without a GPU
// to offload to.
function isGpuBackend(backend: Backend): boolean {
  return backend !== "cpu";
}

// Device nodes bind-mounted into the container, beyond `appliance`. `cpu`
// and `cuda` need none here -- cuda's GPU access comes from the `deploy`
// reservation below, not a device node.
function devicesFor(backend: Backend): string[] {
  switch (backend) {
    case "musa":
      return ["/dev/mtgpu:/dev/mtgpu", "/dev/dri:/dev/dri"];
    case "intel":
    case "vulkan":
      return ["/dev/dri:/dev/dri"];
    case "cuda":
    case "cpu":
      return [];
  }
}

function indent(lines: string[], spaces: number): string[] {
  const pad = " ".repeat(spaces);
  return lines.map((line) => (line.length === 0 ? line : `${pad}${line}`));
}

function renderService(plan: ComposePlan, model: { entry: ModelEntry; service: string }): string[] {
  const { entry, service } = model;
  const modelPath = `/models/${entry.id}/${entry.file}`;
  const lines: string[] = [];

  lines.push(`${service}:`);
  lines.push(`  image: ${plan.image}`);
  lines.push("  restart: unless-stopped");
  lines.push("  networks:");
  lines.push("    - appliance");
  lines.push("  volumes:");
  lines.push(`    - \${APPLIANCE_MODELS_DIR:-./models}/${entry.id}/${entry.file}:${modelPath}:ro`);

  const devices = devicesFor(plan.backend);
  if (devices.length > 0) {
    lines.push("  devices:");
    for (const device of devices) {
      lines.push(`    - "${device}"`);
    }
  }

  lines.push("  command:");
  lines.push("    - --model");
  lines.push(`    - ${modelPath}`);
  lines.push("    - --alias");
  lines.push(`    - ${entry.id}`);
  lines.push("    - --host");
  lines.push("    - 0.0.0.0");
  lines.push("    - --port");
  lines.push('    - "8080"');
  lines.push("    - --ctx-size");
  lines.push(`    - "${entry.ctx}"`);
  if (isGpuBackend(plan.backend)) {
    lines.push("    - --n-gpu-layers");
    lines.push('    - "999"');
    lines.push("    - --verbosity");
    lines.push('    - "4"');
  } else {
    lines.push("    - --threads");
    lines.push(`    - "${plan.threads}"`);
  }

  if (plan.backend === "cuda") {
    lines.push("  deploy:");
    lines.push("    resources:");
    lines.push("      reservations:");
    lines.push("        devices:");
    lines.push("          - driver: nvidia");
    lines.push("            count: all");
    lines.push("            capabilities: [gpu]");
  }

  lines.push("  healthcheck:");
  lines.push('    test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/health || exit 1"]');
  lines.push("    interval: 10s");
  lines.push("    timeout: 5s");
  lines.push("    retries: 60");
  lines.push("    start_period: 300s");

  return lines;
}

/**
 * Renders `compose.models.yml`'s full text: the banner, then one
 * `llamacpp-<id>` service per model in `plan.models`, indented under a
 * single top-level `services:` key. No `ports:` on any service -- these are
 * reachable only on the `appliance` network, by service name; `appliance`
 * itself is declared (as a plain bridge) in `compose.yml`, so this overlay
 * does not redeclare it.
 */
export function renderComposeModels(plan: ComposePlan): string {
  const out: string[] = [BANNER, "", "services:"];

  plan.models.forEach((model, index) => {
    if (index > 0) {
      out.push("");
    }
    out.push(...indent(renderService(plan, model), 2));
  });

  return `${out.join("\n")}\n`;
}

// llama-swap bundles its own llama-server binary at this fixed path in every
// `ghcr.io/mostlygeek/llama-swap:<backend>` image (verified by inspecting the
// `:vulkan` image directly: `/app/llama-server`, `WorkingDir /app`,
// entrypoint `/app/llama-swap -config /app/config.yaml -watch-config`) --
// unlike `compose.models.yml`, there is no separate `image:` per model here,
// so the binary path is a constant, not derived from `plan.image`.
const LLAMA_SWAP_SERVER_BIN = "/app/llama-server";

/**
 * Renders one llama-swap `models.<id>` entry: a `cmd:` block flag-compatible
 * with `renderService`'s own llama-server invocation (same `--ctx-size`,
 * `--host`, `--alias`, and the same GPU-vs-CPU flag choice), except the port
 * is llama-swap's own `${PORT}` macro (assigned per model at load time, not
 * the fixed `8080` every `compose.models.yml` service publishes only on the
 * "appliance" network) and there is no `--port` value to quote -- llama-swap
 * substitutes it into the command line itself. `proxy:` is deliberately
 * omitted: its documented default (`http://localhost:${PORT}`) is exactly
 * right whenever `${PORT}` is used in `cmd`, which it always is here.
 */
function renderLlamaSwapModel(
  plan: ComposePlan,
  model: { entry: ModelEntry; service: string },
): string[] {
  const { entry } = model;
  const modelPath = `/models/${entry.id}/${entry.file}`;

  const cmd: string[] = [
    LLAMA_SWAP_SERVER_BIN,
    // Escaped so JS never interpolates it -- this is llama-swap's OWN macro,
    // substituted by llama-swap itself when it spawns this command, not a
    // value this module ever knows.
    `--port \${PORT}`,
    `--model ${modelPath}`,
    `--alias ${entry.id}`,
    "--host 0.0.0.0",
    `--ctx-size ${entry.ctx}`,
  ];
  if (isGpuBackend(plan.backend)) {
    cmd.push("--n-gpu-layers 999", "--verbosity 4");
  } else {
    cmd.push(`--threads ${plan.threads}`);
  }

  const lines: string[] = [];
  // The model's own id is the key llama-swap's `models:` map (and so, via
  // LiteLLM's `model: openai/<id>`, litellm.ts's local-model routing) is
  // matched by -- never `service` (the Compose service name), which has no
  // meaning inside the single `llamaswap` container.
  lines.push(`${entry.id}:`);
  lines.push("  cmd: |");
  for (const line of cmd) {
    lines.push(`    ${line}`);
  }
  return lines;
}

/**
 * Renders llama-swap's `config.yaml`: the banner, then one `models.<id>`
 * entry per model in `plan.models`, each with its own `llama-server` command
 * line under llama-swap's single process. No `routing:`/`groups:` section is
 * emitted -- llama-swap's own undeclared default (one exclusive, swapping
 * group containing every model) is exactly the property this overlay exists
 * to buy: at most one model resident at a time, verified against the bundled
 * `ghcr.io/mostlygeek/llama-swap:vulkan` image's own `config.yaml` example,
 * whose comment on `group1` reads "reproduces llama-swap's default
 * behaviour: only one model runs at a time across the entire instance."
 */
export function renderLlamaSwapConfig(plan: ComposePlan): string {
  const out: string[] = [BANNER, "", "models:"];

  plan.models.forEach((model, index) => {
    if (index > 0) {
      out.push("");
    }
    out.push(...indent(renderLlamaSwapModel(plan, model), 2));
  });

  return `${out.join("\n")}\n`;
}
