/**
 * Renders LiteLLM's local `config.local.yaml`: a `model_list` pointing at
 * the `llama-server` containers Task 7's `compose.models.yml` stands up on
 * the `appliance` network, plus (opt-in) the four OpenRouter models already
 * deployed in `config.server.yaml`.
 *
 * Emitted as text, not via a YAML library: this package is stdlib-only (see
 * compose.ts's header for the fuller rationale), and the shape needed here
 * -- a `model_list` sequence plus one fixed `general_settings` block -- is
 * small enough to get byte-exact by hand.
 *
 * `general_settings` below is copied verbatim from `A/litellm/config.yaml`,
 * comment included. `litellm_key_header_name: x-litellm-api-key` is not
 * decoration: the hub mints scoped LiteLLM keys (`apps/hub/src/services/
 * llm/keys.ts`) and every caller -- the hub's `/keys` endpoint, the chat
 * app, the e2e -- sends the key in that header, not `Authorization`. Drop
 * this line and every member 401s, for a reason that looks like a broken
 * key rather than a missing config line.
 */

export interface LitellmPlan {
  models: Array<{ id: string; service: string }>;
  openrouter: boolean;
}

const BANNER = "# GENERATED by bin/prepare.sh -- do not edit by hand.";

// The four models deployed in `A/litellm/config.server.yaml`, copied
// verbatim (name and `model:` value) so the local appliance's opt-in cloud
// list never drifts from what's actually live on httpeers.net. Checked
// against that file on 2026-09-20; if the server's list changes, update
// here too -- this module does not read `config.server.yaml` at run time
// (it's one of the files this package must never touch), so the copy is
// by hand.
export const OPENROUTER_MODELS: Array<{ name: string; model: string }> = [
  { name: "gpt-4o-mini", model: "openrouter/openai/gpt-4o-mini" },
  { name: "claude-haiku-4.5", model: "openrouter/anthropic/claude-haiku-4.5" },
  { name: "gemini-2.5-flash", model: "openrouter/google/gemini-2.5-flash" },
  { name: "llama-3.3-70b", model: "openrouter/meta-llama/llama-3.3-70b-instruct" },
];

function renderLocalEntry(model: { id: string; service: string }): string[] {
  const lines: string[] = [];
  lines.push(`- model_name: ${model.id}`);
  lines.push("  litellm_params:");
  lines.push(`    model: openai/${model.id}`);
  lines.push(`    api_base: http://${model.service}:8080/v1`);
  // llama-server doesn't check this at all, but LiteLLM's schema requires
  // `api_key` to be present on every entry; `local` is a placeholder, never
  // a real credential, so it's safe to write literally.
  lines.push(
    "    api_key: local  # placeholder -- llama-server ignores it, LiteLLM requires the field",
  );
  return lines;
}

function renderOpenrouterEntry(model: { name: string; model: string }): string[] {
  const lines: string[] = [];
  lines.push(`- model_name: ${model.name}`);
  lines.push("  litellm_params:");
  lines.push(`    model: ${model.model}`);
  // Never inlined -- read from the environment at LiteLLM's start, same as
  // `config.server.yaml`.
  lines.push("    api_key: os.environ/OPENROUTER_API_KEY");
  return lines;
}

function indent(lines: string[], spaces: number): string[] {
  const pad = " ".repeat(spaces);
  return lines.map((line) => (line.length === 0 ? line : `${pad}${line}`));
}

/**
 * Renders the local config's full text: the banner, `model_list` (local
 * models first, so the picker's default is local; the four OpenRouter
 * models appended only when `plan.openrouter` is true), then
 * `general_settings` verbatim from `A/litellm/config.yaml`.
 */
export function renderLitellmConfig(plan: LitellmPlan): string {
  const out: string[] = [BANNER, "", "model_list:"];

  for (const model of plan.models) {
    out.push(...indent(renderLocalEntry(model), 2));
  }

  if (plan.openrouter) {
    for (const model of OPENROUTER_MODELS) {
      out.push(...indent(renderOpenrouterEntry(model), 2));
    }
  }

  out.push("");
  out.push("general_settings:");
  out.push("  master_key: os.environ/LITELLM_MASTER_KEY");
  out.push("  # Retargets LiteLLM's own key extraction (server-side) and the dashboard JS");
  out.push("  # (client-side, via the login response's `auth_header_name`) to");
  out.push("  # `x-litellm-api-key`; with it set, LiteLLM ignores `Authorization` for keys");
  out.push(
    "  # (MEASURED, docs/research/2026-09-15-llm-appliance-spikes/litellm-ui-through-mesh.md",
  );
  out.push("  # Q3). It was introduced because the mesh token also lived in `Authorization`;");
  out.push("  # it no longer does (the mesh uses `x-httpeers-token`), but the hub's `/keys`,");
  out.push("  # the chat app and the e2e all send the key here, and the hub's passthrough");
  out.push("  # moves a Bearer key it finds in `Authorization` (the Playground's) here too.");
  out.push("  litellm_key_header_name: x-litellm-api-key");

  return `${out.join("\n")}\n`;
}
