#!/usr/bin/env bash
# Proves the GPU was actually used, which `docker compose config` cannot.
#
# Works under BOTH deployment shapes: the default N x llama-server path
# (compose.models.yml's llamacpp-<id> services, one resident per model) and
# the --llamaswap alternative (a single llamaswap service; compose.models.yml
# is still generated by prepare either way, so its llamacpp-<id> services are
# always DEFINED, but under --llamaswap they are never started).
#
# compose.llamaswap.yml is always referenced below -- it is checked in, not
# generated, and compose.llamaswap.yml's own header says referencing it is
# harmless as long as no bare `up` names it (see README.md's "llama-swap
# alternative" and compose.llamaswap.yml itself). Referencing it here never
# starts anything; it only makes `config`/`ps` aware of the `llamaswap`
# service when a deployment happens to be running it.
#
# The mode is read from what is actually RUNNING, not from which generated
# files happen to exist on disk: llamaswap/config.yaml is gitignored and can
# survive on disk from an earlier --llamaswap prepare run (VERIFIED on this
# host on 2026-09-21: the file was present while the running appliance was in
# three-file/N-server mode). Checking file presence would have reintroduced
# exactly the false-alarm bug this fixes, just keyed on a different stale
# artifact instead of on an unstarted service. `docker compose ps --services
# --status running` is the one source of truth this script trusts.
set -euo pipefail
cd "$(dirname "$0")/.."
BACKEND="$(grep -E '^LLAMA_BACKEND=' .env | cut -d= -f2-)"

FILES=(-f compose.yml -f compose.local.yml -f compose.models.yml -f compose.llamaswap.yml)

RUNNING="$(docker compose "${FILES[@]}" ps --services --status running)"

CHECKED=0
for service in $(docker compose "${FILES[@]}" config --services | grep '^llamacpp-'); do
  if ! printf '%s\n' "$RUNNING" | grep -qx "$service"; then
    # Defined (compose.models.yml is always generated) but never started --
    # the expected shape under --llamaswap. Not a failed GPU check: there is
    # no container, so there are no logs to prove or disprove anything.
    echo "SKIP $service: defined but not running (this deployment does not start it)"
    continue
  fi
  CHECKED=1
  LOG="$(docker compose "${FILES[@]}" logs --no-color "$service" 2>&1)"
  printf '%s' "$LOG" | docker run --rm -i -v "$(cd ../.. && pwd):/work" -w /work node:22-alpine \
    node --experimental-strip-types apps/appliance-prepare/src/verify-backend-cli.ts "$BACKEND" "$service"
done

if [ "$CHECKED" -eq 0 ]; then
  if printf '%s\n' "$RUNNING" | grep -qx "llamaswap"; then
    # llama-swap loads models lazily, on first request -- a running
    # llamaswap container proves nothing about the backend by itself (no
    # llama-server process has necessarily started yet). This script does
    # not drive a request to force a load; it only avoids the false GPU
    # alarm. See scripts/verify-backend.sh's own header and BENCHMARK.md.
    echo "llamaswap is running: no llamacpp-* service is started under --llamaswap by design," \
      "so there is nothing to check here -- verify GPU use through llamaswap's own logs after" \
      "a real request has loaded a model."
  else
    echo "verify-backend: no llamacpp-* service and no llamaswap service is running -- nothing to check" >&2
    exit 1
  fi
fi
