import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { BACKEND_IMAGES } from "../src/backend.js";
import { renderComposeModels, renderLlamaSwapConfig } from "../src/compose.js";

const SNAPSHOTS = resolve(dirname(fileURLToPath(import.meta.url)), "snapshots");

// The brief's ModelEntry literals predate Task 4's `fileSize` field; it is
// added here (per controller ruling, same as tests/download.test.ts) so this
// typechecks against the current ModelEntry. compose.ts never reads
// `fileSize` or `repo`, so its value is arbitrary.
const PLAN = (backend: keyof typeof BACKEND_IMAGES) => ({
  backend,
  image: BACKEND_IMAGES[backend],
  threads: 8,
  models: [
    {
      entry: { id: "small-a", repo: "Org/A", file: "a.gguf", ctx: 4096, fileSize: 1 },
      service: "llamacpp-small-a",
    },
    {
      entry: { id: "small-b", repo: "Org/B", file: "b.gguf", ctx: 8192, fileSize: 1 },
      service: "llamacpp-small-b",
    },
  ],
});

describe("renderComposeModels", () => {
  it.each(["cpu", "cuda", "vulkan", "intel", "musa"] as const)(
    "renders %s exactly as the checked-in snapshot",
    async (backend) => {
      const expected = await readFile(resolve(SNAPSHOTS, `compose-${backend}.yml`), "utf8");
      expect(renderComposeModels(PLAN(backend))).toBe(expected);
    },
  );

  it("gives CUDA a device reservation and no /dev/dri mount", () => {
    const yaml = renderComposeModels(PLAN("cuda"));
    expect(yaml).toMatch(/driver: nvidia/);
    expect(yaml).toMatch(/capabilities: \[gpu\]/);
    expect(yaml).not.toMatch(/\/dev\/dri/);
  });

  it("gives intel and vulkan a /dev/dri device and no nvidia reservation", () => {
    for (const backend of ["intel", "vulkan"] as const) {
      const yaml = renderComposeModels(PLAN(backend));
      expect(yaml, backend).toMatch(/\/dev\/dri:\/dev\/dri/);
      expect(yaml, backend).not.toMatch(/driver: nvidia/);
    }
  });

  it("gives cpu neither, and passes --threads", () => {
    const yaml = renderComposeModels(PLAN("cpu"));
    expect(yaml).not.toMatch(/\/dev\/dri/);
    expect(yaml).not.toMatch(/driver: nvidia/);
    expect(yaml).toMatch(/--threads/);
  });

  it("offloads all layers on every GPU backend and none on cpu", () => {
    for (const backend of ["cuda", "vulkan", "intel", "musa"] as const) {
      expect(renderComposeModels(PLAN(backend)), backend).toMatch(/--n-gpu-layers/);
    }
    expect(renderComposeModels(PLAN("cpu"))).not.toMatch(/--n-gpu-layers/);
  });

  it("mounts the model file read-only, by its own path", () => {
    expect(renderComposeModels(PLAN("cpu"))).toMatch(/\/models\/small-a\/a\.gguf:ro/);
  });

  it("names one service per model and never collides", () => {
    const yaml = renderComposeModels(PLAN("cpu"));
    expect(yaml).toMatch(/^ {2}llamacpp-small-a:$/m);
    expect(yaml).toMatch(/^ {2}llamacpp-small-b:$/m);
  });

  it("publishes no ports at all -- llama-server is reachable only on the appliance network", () => {
    for (const backend of ["cpu", "cuda", "vulkan", "intel", "musa"] as const) {
      expect(renderComposeModels(PLAN(backend)), backend).not.toMatch(/^\s*ports:/m);
    }
  });

  it("begins with the generated-file banner", () => {
    expect(renderComposeModels(PLAN("cpu")).startsWith("# GENERATED by bin/prepare.sh")).toBe(true);
  });

  it("emits no Compose merge tags, so it works on 2.24 through 5.x", () => {
    for (const backend of ["cpu", "cuda", "vulkan", "intel", "musa"] as const) {
      expect(renderComposeModels(PLAN(backend)), backend).not.toMatch(/!reset|!override/);
    }
  });
});

describe("renderLlamaSwapConfig", () => {
  it("defines one model per manifest entry, each with its own llama-server command", () => {
    const config = renderLlamaSwapConfig(PLAN("cpu"));
    expect(config).toMatch(/small-a:/);
    expect(config).toMatch(/small-b:/);
    expect(config).toMatch(/\/models\/small-a\/a\.gguf/);
  });

  it("passes the per-model context size through", () => {
    expect(renderLlamaSwapConfig(PLAN("cpu"))).toMatch(/--ctx-size\s+8192/);
  });

  it("begins with the generated-file banner", () => {
    expect(renderLlamaSwapConfig(PLAN("cpu")).startsWith("# GENERATED by bin/prepare.sh")).toBe(
      true,
    );
  });
});
