import { describe, expect, it } from "vitest";
import { renderLitellmConfig } from "../src/litellm.js";

const PLAN = { models: [{ id: "small-a", service: "llamacpp-small-a" }], openrouter: false };

describe("renderLitellmConfig", () => {
  it("names each local model at its own service on the appliance network", () => {
    const yaml = renderLitellmConfig(PLAN);
    expect(yaml).toMatch(/model_name: small-a/);
    expect(yaml).toMatch(/api_base: http:\/\/llamacpp-small-a:8080\/v1/);
  });

  it("carries the key header setting, without which the hub's minted keys are rejected", () => {
    expect(renderLitellmConfig(PLAN)).toMatch(/litellm_key_header_name: x-litellm-api-key/);
  });

  it("reads the master key from the environment, never inlining it", () => {
    const yaml = renderLitellmConfig(PLAN);
    expect(yaml).toMatch(/master_key: os\.environ\/LITELLM_MASTER_KEY/);
    expect(yaml).not.toMatch(/sk-[0-9a-f]{8}/);
  });

  it("omits every OpenRouter model by default", () => {
    expect(renderLitellmConfig(PLAN)).not.toMatch(/openrouter/);
  });

  it("appends the four OpenRouter models when a key is present, reading it from the environment", () => {
    const yaml = renderLitellmConfig({ ...PLAN, openrouter: true });
    for (const name of ["gpt-4o-mini", "claude-haiku-4.5", "gemini-2.5-flash", "llama-3.3-70b"]) {
      expect(yaml, name).toContain(name);
    }
    expect(yaml).toMatch(/api_key: os\.environ\/OPENROUTER_API_KEY/);
  });

  it("keeps the local models first, so the picker's default is local", () => {
    const yaml = renderLitellmConfig({ ...PLAN, openrouter: true });
    expect(yaml.indexOf("small-a")).toBeLessThan(yaml.indexOf("gpt-4o-mini"));
  });

  it("begins with the generated-file banner", () => {
    expect(renderLitellmConfig(PLAN).startsWith("# GENERATED by bin/prepare.sh")).toBe(true);
  });
});
